<a href="https://colab.research.google.com/github/sudharsansanthanaraja/workbook1/blob/main/numpynotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# initializing a numpy array with zeros.
n7 = np.zeros((3,4,5), dtype = 'int64')
n7

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [ ]:
#initializing a numpy array with random values.

A = np.random.randint(100, 150, 15, dtype = 'int32')
A

array([134, 131, 130, 112, 119, 106, 122, 144, 112, 101, 139, 125, 115,
       114, 100])

In [ ]:
# initializing a numpy array with a range of values - the last paramater is the skip value.

n1 = np.arange(23,45, 3)
n1

array([23, 26, 29, 32, 35, 38, 41, 44])

In [ ]:
# initializing a numpy array with identical values.

n2 = np.full((4, 15), 3)
n2

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
# horizontally combining two arrays

n3 = np.array([2,4,6,7,8])
n4 = np.array([3,5,7,9,10])

np.hstack((n3,n4))

array([ 2,  4,  6,  7,  8,  3,  5,  7,  9, 10])

In [ ]:
# vertically combining two arrays.
np.vstack((n3,n4))

array([[ 2,  4,  6,  7,  8],
       [ 3,  5,  7,  9, 10]])

In [ ]:
# column stack - combines adjacent values.

np.column_stack((n3,n4))

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 7,  9],
       [ 8, 10]])

In [ ]:
# intersection with numpy arrays.

np.intersect1d(n3,n4)

array([7])

In [ ]:
# difference with numpy arrays.

np.setdiff1d(n3,n4)

array([2, 4, 6, 8])

In [ ]:
# totalling an array.

np.sum([n3, n4])

61

In [ ]:
# totalling across axes.
# 1st axis

np.sum([n3, n4], axis = 0)

array([ 5,  9, 13, 16, 18])

In [ ]:
# 2nd axis

np.sum([n3, n4], axis = 1)

array([27, 34])

In [ ]:
# mean

n3.mean()

5.4

In [ ]:
# median

np.median(n3)

6.0

In [ ]:
# standard deviation

np.std(n4)

2.5612496949731396

In [ ]:
#matrix

n5 = np.array([[1,2,3],
              [4,5,7],
              [6,8,10]])
n5

array([[ 1,  2,  3],
       [ 4,  5,  7],
       [ 6,  8, 10]])

In [ ]:
n6 = np.array([[10,20,30],
             [23,45,67],
             [16,19,17]])
n6

array([[10, 20, 30],
       [23, 45, 67],
       [16, 19, 17]])

In [ ]:
#indexing a matrix

n5[2]

array([ 6,  8, 10])

In [ ]:
#matrix multiplication

n5.dot(n6)

array([[104, 167, 215],
       [267, 438, 574],
       [404, 670, 886]])

In [ ]:
#saving a numpy array
np.save('new_numpy', n6)

In [ ]:
#loading a numpy array

np.load('new_numpy.npy')

array([[10, 20, 30],
       [23, 45, 67],
       [16, 19, 17]])

Boolean Arrays

In NumPy, boolean arrays are straightforward NumPy arrays with array components that are either “True” or “False.”

In [ ]:
# Basic syntax

n8 = np.array([0,1,2,3,4,5,6,7])
print('Oridnary array: {}'.format(n8))

n8bool = np.array(n8, dtype = 'bool')
print('Boolean array: {}'.format(n8bool))

Oridnary array: [0 1 2 3 4 5 6 7]
Boolean array: [False  True  True  True  True  True  True  True]


In [ ]:
# filtering components of an array

n8[n8 >=3]

array([3, 4, 5, 6, 7])

In [ ]:
# broadcasiting a boolean array

a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


LINEAR ALGEBRA with NumPy

Basic Operations:

In [ ]:
# 1. dot multiplication of arrays
np.dot(n6,n5)

array([[ 270,  360,  470],
       [ 605,  807, 1054],
       [ 194,  263,  351]])

In [ ]:
# 2. vdot multiplication - vector multiplication

array1 = np.array([0,1,2,3])
array2 = np.array([4,5,6,7])

np.vdot(array1,array2)

38